version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PG_HOST=db
      - PG_SCHEMA=public
      - PG_DATABASE=devrateDB
      - PG_USERNAME=admin
      - PG_PASSWORD=root
      - ZOOM_ISSUER_URL=http://wiremock:8080
      - ZOOM_API_URL=http://wiremock:8080
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - db
      - mailhog
      - wiremock
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=devrateDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d devrateDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1025" ]
      interval: 30s
      timeout: 10s
      retries: 3
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    ports:
      - "8089:8080"
    volumes:
      - ./src/main/resources/wiremock/mappings:/home/wiremock/mappings:ro
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]
volumes:
  postgres_data:
