version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PG_HOST=db
      - PG_DATABASE=devrateDB
      - PG_USERNAME=admin
      - PG_PASSWORD=root
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=devrateDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d devrateDB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
