services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=devrateDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d devrateDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1025" ]
      interval: 30s
      timeout: 10s
      retries: 3
  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    ports:
      - "9324:9324" # REST API
      - "9325:9325" # Web interface
    volumes:
      - ./src/main/resources/elasticmq.conf:/opt/elasticmq.conf
    command: -Dconfig.file=/opt/elasticmq.conf
volumes:
  postgres_data:
