openapi: 3.0.3
info:
  title: DevRate Platform API
  description: API endpoints for managing user registration, interview processes, and candidate evaluations on the Devrate platform.
  termsOfService: DevRate
  contact:
    name: DevRate
    url: https://devrate.com
    email: devrate@gmail.com
  license:
    name: DevRate
    url: https://devrate.com
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080
    description: Local environment
  - url: https://devrate.com
    description: Production environment
tags:
  - name: registration
    description: endpoint for user registration
  - name: Notification
    description: Operations related to sending notifications
  - name: authentication
    description: Endpoints for user authentication
  - name: password-reset
    description: Endpoints for password reset functionality
paths:
  /auth/signup:
    post:
      tags:
        - registration
      description: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /notify/{login}:
    post:
      tags:
        - Notification
      summary: Send a notification to a specific user
      description: Sends a notification to a specific user identified by their login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      parameters:
        - in: path
          name: login
          required: true
          schema:
            type: string
          description: The login of the user to send the notification to
      responses:
        '200':
          description: Notification sent successfully
        '400':
          description: Bad request, invalid parameters
        '404':
          description: User not found
        '500':
          description: Internal server error
  /auth/signup/{id}/{code}:
    get:
      tags:
        - registration
      description: Confirming the user's email by matching the code
      operationId: confirmEmail
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The unique identifier of the user for whom the email is being confirmed.
        - in: path
          name: code
          required: true
          schema:
            type: string
          description: The confirmation code to be checked against the stored code.
      responses:
        '200':
          description: Email confirmation code successfully confirmed
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Bad request, e.g., invalid ID or code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User or code not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/password-reset:
    post:
      tags:
        - password-reset
      summary: Request Password Reset Link
      description: Requests a password reset link to be sent to the given email.
      operationId: requestPasswordReset
      parameters:
        - in: query
          name: email
          required: true
          schema:
            type: string
            format: email
          description: The email address of the user requesting a password reset.
      responses:
        '200':
          description: Password reset link sent successfully.
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Bad request, e.g., invalid email format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/password-reset/{code}:
    post:
      tags:
        - password-reset
      summary: Reset Password
      description: Resets the user's password using a unique code received in the password reset link.
      operationId: resetPassword
      parameters:
        - in: path
          name: code
          required: true
          schema:
            type: string
          description: The unique code received in the password reset link.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              description: The new password to be set for the user account.
      responses:
        '200':
          description: Password reset successfully.
          content:
            application/json:
              schema:
                type: boolean
        '400':
          description: Bad request, e.g., invalid code or password format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/signin:
    post:
      tags:
        - authentication
      summary: Authenticate user
      description: Authenticates a user based on the provided login credentials.
      operationId: authenticateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginDto'
        '400':
          description: Bad request, e.g., missing or invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized, e.g., invalid email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    UserDto:
      type: object
      description: Required information for registering a new user
      properties:
        email:
          type: string
          format: email
          description: The email chosen by the user for their account
        firstName:
          type: string
          description: The first name inputted by the user
        lastName:
          type: string
          description: The last name inputted by the user
        country:
          type: string
          description: The country chosen by the user for their account
        subscribed:
          type: boolean
          description: Flag indicating whether the user is subscribed to the newsletter
        verified:
          type: boolean
          description: Flag indicating whether the user's email is verified
        password:
          type: string
          description: The password chosen by the user for their account
        createdAt:
          type: string
          format: date-time
          description: The timestamp when the user account was created
          readOnly: true
      required:
        - email
        - firstName
        - lastName
        - country
        - password
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: The error message
    Notification:
      type: object
      properties:
        text:
          type: string
          description: The text of the notification
    LoginDto:
      type: object
      properties:
        email:
          type: string
          format: email
          description: Email address of the user
        password:
          type: string
          format: password
          description: Password of the user
      required:
        - email
        - password