databaseChangeLog:
  - changeSet:
      id: 11-02-2024_03_create-table-user-security
      author: Dmytro Abalmas
      changes:
        - createTable:
            tableName: user_security
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: password
                  type: VARCHAR(245)
                  constraints:
                    nullable: false
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    unique: true
                    nullable: false
              - column:
                  name: user_role_id
                  type: BIGINT
                  constraints:
                    nullable: false