openapi: 3.0.3
info:
  title: DevRate Platform API
  description: API endpoints for managing user registration, interview processes, and candidate evaluations on the DevRate platform.
  termsOfService: DevRate
  contact:
    name: DevRate
    url: https://devrate.com
    email: devrate@gmail.com
  license:
    name: DevRate
    url: https://devrate.com
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080
    description: Local environment
  - url: https://server.skillzzy.com
    description: Production environment
tags:
  - name: Registration
    description: endpoint for user registration
  - name: Notification
    description: Operations related to sending notifications
  - name: Authentication
    description: Endpoints for user authentication
  - name: OAuth
    description: Endpoints for user authentication via OAuth
  - name: Password-Reset
    description: Endpoints for password reset functionality
  - name: Refresh-Token
    description: Endpoints for refresh token functionality
  - name: User Info
    description: Endpoints for user personal info functionality
  - name: Employment Records
    description: Endpoints for user Employment Records management
  - name: Achievement
    description: Endpoints for user achievement management
  - name: Bookmark
    description: Endpoints for user bookmark management
  - name: Interview
    description: Endpoints for interview management
  - name: Interview Request
    description: Endpoints for interview request management
  - name: Interview History
    description: Endpoints for interview history management
  - name: Interview Feedback
    description: Endpoints for interview feedback management
  - name: Static Data
    description: Endpoints for retrieving static data
  - name: Specialization
    description: Endpoints for user Specialization management
  - name: Mastery
    description: Endpoints for user Mastery management
  - name: Skill
    description: Endpoints for user Skill management
  - name: Event
    description: Endpoints for managing calendar events
  - name: Event History
    description: Endpoints for managing calendar event histories
  - name: Chat
    description: Endpoints for managing chat messaging
  - name: Profile Settings
    description: Endpoints for managing profile settings
paths:
  /auth/signup:
    $ref: './paths/auth/signup.yaml'
  /auth/confirm-activation-account:
    $ref: './paths/auth/confirm-activation-account.yaml'
  /auth/signup/confirm:
    $ref: './paths/auth/signup-code.yaml'
  /auth/signup/resend-code:
    $ref: './paths/auth/signup-resend-code.yaml'
  /auth/request-password-reset:
    $ref: './paths/auth/request-password-reset.yaml'
  /auth/password-reset:
    $ref: './paths/auth/password-reset.yaml'
  /auth/signin:
    $ref: './paths/auth/signin.yaml'
  /auth/logout:
    $ref: './paths/auth/logout.yaml'
  /auth/refresh-token:
    $ref: './paths/auth/refresh-token.yaml'
  /auth/oauth/redirect/linkedIn:
    $ref: './paths/auth/oauth-redirect-linkedIn.yaml'
  /auth/oauth/redirect/google:
    $ref: './paths/auth/oauth-redirect-google.yaml'
  /auth/oauth/authorize:
    $ref: './paths/auth/oauth-authorize.yaml'
  /notifications:
    $ref: './paths/notifications/notifications.yaml'
  /ws/notifications:
    $ref: './paths/notifications/ws-notifications.yaml'
  /users/{id}:
    $ref: './paths/users/users-id.yaml'
  /users:
    $ref: './paths/users/users.yaml'
  /users/{userId}/language-proficiencies:
    $ref: './paths/users/users-id-languageProficiencies.yaml'
  /users/{userId}/pictures:
    $ref: './paths/users/users-id-pictures.yaml'
  /users/{userId}/contacts:
    $ref: './paths/users/users-id-contacts.yaml'
  /users/{userId}/educations:
    $ref: './paths/users/users-id-educations.yaml'
  /users/{userId}/private-skills:
    $ref: './paths/users/users-id-private-skills.yaml'
  /users/{userId}/public-skills:
    $ref: './paths/users/users-id-public-skills.yaml'
  /educations/{id}:
    $ref: './paths/educations/educations-id.yaml'
  /users/{userId}/employment-records:
    $ref: './paths/users/users-id-employmentRecords.yaml'
  /employment-records/{id}:
    $ref: './paths/employmentRecords/employmentRecords-id.yaml'
  /users/{userId}/achievements:
    $ref: './paths/users/users-id-achievements.yaml'
  /achievements/{id}:
    $ref: './paths/achievements/achievements-id.yaml'
  /users/{userId}/bookmarks:
    $ref: './paths/users/users-id-bookmarks.yaml'
  /bookmarks/{id}:
    $ref: './paths/bookmarks/bookmarks-id.yaml'
  /interview-histories?page=1&size=10:
    $ref: './paths/interviewHistories/interview-histories.yaml'
  /interview-histories/{id}:
    $ref: './paths/interviewHistories/interview-histories-id.yaml'
  /interview-histories/statistics?from={fromDateTime}&to={toDateTime}:
    $ref: './paths/interviewHistories/interview-histories-statistics.yaml'
  /data/languageproficiency/{filename}:
    $ref: './paths/data/data-languageproficiency-filename.yaml'
  /data/user/{filename}:
    $ref: './paths/data/data-user-filename.yaml'
  /data/specialization/{filename}:
    $ref: './paths/data/data-specialization-filename.yaml'
  /data/faq/{filename}:
    $ref: './paths/data/data-faq-filename.yaml'
  /users/{userId}/specializations:
    $ref: './paths/users/users-id-specializations.yaml'
  /specializations/{id}:
    $ref: './paths/specializations/specializations-id.yaml'
  /specializations/{id}/main-mastery:
    $ref: './paths/specializations/specializations-id-mainMastery.yaml'
  /specializations/{id}/masteries:
    $ref: './paths/specializations/specializations-id-masteries.yaml'
  /specializations:
    $ref: './paths/specializations/specializations.yaml'
  /specializations/{id}/set-main:
    $ref: './paths/specializations/specializations-id-setMain.yaml'
  /specializations/{specId}/set-main-mastery/{masteryId}:
    $ref: './paths/specializations/specializations-id-setMainMastery-masteryId.yaml'
  /masteries/{id}:
    $ref: './paths/masteries/masteries-id.yaml'
  /masteries/{id}/skills/all:
    $ref: './paths/masteries/masteries-id-skills-all.yaml'
  /masteries/{id}/soft-skills:
    $ref: './paths/masteries/masteries-id-soft-skills.yaml'
  /masteries/{id}/hard-skills:
    $ref: './paths/masteries/masteries-id-hard-skills.yaml'
  /masteries/{id}/skills:
    $ref: './paths/masteries/masteries-id-skills.yaml'
  /masteries/{id}/skills/bulk:
    $ref: './paths/masteries/masteries-id-skills-bulk.yaml'
  /masteries:
    $ref: './paths/masteries/masteries.yaml'
  /skills/{id}:
    $ref: './paths/skills/skills-id.yaml'
  /skills/{id}/calculate-mark/{mark}:
    $ref: './paths/skills/skills-id-calculateMark-mark.yaml'
  /skills/{id}/hide/{hide}:
    $ref: './paths/skills/skills-id-hide-hide.yaml'
  /masteries/{masteryId}/history:
    $ref: './paths/masteries/masteries-id-mastery-history.yaml'
  /users/{userId}/specializations/main-mastery/skills:
    $ref: './paths/users/users-id-specializations-main-mastery-skills.yaml'
  /users/search:
    $ref: './paths/users/users-search.yaml'
  /users/{userId}/notifications:
    $ref: './paths/users/users-id-notifications.yaml'
  /users/{userId}/notification/send:
    $ref: './paths/users/users-id-notification-send.yaml'
  /users/{userId}/platform-feedbacks:
    $ref: './paths/users/users-id-platform-feedbacks.yaml'
  /interview-requests:
    $ref: './paths/interviewRequest/interview-requests.yaml'
  /interview-requests/{id}:
    $ref: './paths/interviewRequest/interview-requests-id.yaml'
  /interview-requests/masteries/{masteryId}:
    $ref: './paths/interviewRequest/interview-requests-masteries-masteryId.yaml'
  /interview-requests/{id}/add-timeslots:
    $ref: './paths/interviewRequest/interview-requests-id-add-timeslots.yaml'
  /interview-requests/{id}/delete-timeslots:
    $ref: './paths/interviewRequest/interview-requests-id-delete-timeslots.yaml'
  /events?from=2025-02-01&to=2025-02-28:
    $ref: './paths/events/events.yaml'
  /event-histories/events/{id}:
    $ref: './paths/events/event-history.yaml'
  /interviews?page=1&size=5:
    $ref: './paths/interview/interviews.yaml'
  /interviews/{id}:
    $ref: './paths/interview/interviews-id.yaml'
  /interviews/{id}/visible:
    $ref: './paths/interview/interviews-id-visible.yaml'
  /interviews/events/{id}:
    $ref: './paths/interview/interviews-events-id.yaml'
  /interviews/events/closest?from=2025-02-22T12:00:00Z:
    $ref: './paths/interview/interviews-events-closest.yaml'
  /interviews/status-indicator?userTimeZone={zoneName}:
    $ref: './paths/interview/interviews-status-indicator.yaml'
  /interview-feedbacks:
    $ref: './paths/interviewFeedback/interview-feedback.yaml'
  /interview-feedbacks/{id}:
    $ref: './paths/interviewFeedback/interview-feedback-detail-id.yaml'
  /chats:
    $ref: './paths/chats/chats.yaml'
  /chats/{opponentUserId}?page=1&size=10:
    $ref: './paths/chats/chats-opponentUserId.yaml'
  /chat:
    $ref: './paths/chats/ws-chats.yaml'
  /profile-settings/change-email:
    $ref: './paths/profileSettings/change-email.yaml'
  /profile-settings/change-password:
    $ref: './paths/profileSettings/change-password.yaml'
  /profile-settings/account-language:
    $ref: './paths/profileSettings/account-language.yaml'
  /profile-settings/profile-deactivation:
    $ref: './paths/profileSettings/profile-deactivation.yaml'
  /profile-settings/email-subscription:
    $ref: './paths/profileSettings/email-subscription.yaml'
components:
  securitySchemes:
    accessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Access token used for authorizing API requests. Sent in the `Authorization` header.
    idToken:
      type: apiKey
      in: header
      name: ID-Token
      description: ID token used for retrieving user identity information. Sent in the `ID-Token` header.
    refreshToken:
      type: apiKey
      in: cookie
      name: Refresh-Token
      description: Refresh token used to obtain a new access and ID tokens. Sent as an HTTP cookie with the name `Refresh-Token`.
security:
  - accessToken: []
  - idToken: []
  - refreshToken: []