name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Run create-infrastructure workflow
        run: gh workflow run terraform_deploy.yml --ref ${{ github.event.inputs.branch }}

      - name: Run build-and-push-image workflow
        run: gh workflow run build.yml --ref ${{ github.event.inputs.branch }}

      - name: Run deploy-application workflow
        run: gh workflow run deploy_service_to_AWS.yml --ref ${{ github.event.inputs.branch }}
