name: Destroy

on:
  schedule:
    - cron: '00 01 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy (prod, dev, dev_new)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - dev_new

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine environment
        id: determine_env
        run: |
          if [ -z "${{ github.event.inputs.environment }}" ]; then
            ENVIRONMENT="dev"  # Default value for scheduled runs
          else
            ENVIRONMENT="${{ github.event.inputs.environment }}"
          fi
          echo "Selected environment: $ENVIRONMENT"
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV

      - name: Get current branch name
        id: get_branch_name
        run: |
          # Extract branch name from GITHUB_REF
          BRANCH_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/heads\///')
          echo "Current branch: ${BRANCH_NAME}"
          # Save branch name to GitHub Actions environment variable
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Debug DOMAIN variable
        run: |
          echo "Domain from vars: '${{ vars.DOMAIN }}'"

      - name: Run destroy_service workflow
        id: destroy_service
        run: |
          gh workflow run Destroy_Service --ref ${{ env.BRANCH_NAME }} -F environment=${{ env.ENVIRONMENT }}
          echo "Waiting for Destroy_Service to complete..."
          sleep 10
          RUN_ID=$(gh run list --workflow=Destroy_Service --json databaseId,status --limit 1 | jq -r '.[0] | select(.status == "in_progress" or .status == "queued").databaseId')
          if [ -z "$RUN_ID" ]; then
            echo "No in-progress run found. Skipping watch."
          else
            echo "Waiting for workflow run $RUN_ID to complete..."
              gh run watch $RUN_ID --exit-status --interval 15
          fi   

      - name: Run terraform_destroy workflow
        id: terraform_destroy
        if: steps.destroy_service.conclusion == 'success'
        run: |
          gh workflow run Terraform_destroy --ref ${{ env.BRANCH_NAME }} -F environment=${{ env.ENVIRONMENT }}
          echo "Waiting for Terraform_destroy to complete..."
          sleep 10
          RUN_ID=$(gh run list --workflow=Terraform_destroy --json databaseId,status --limit 1 | jq -r '.[0] | select(.status == "in_progress" or .status == "queued").databaseId')
          if [ -z "$RUN_ID" ]; then
            echo "No in-progress run found. Skipping watch."
          else
            echo "Waiting for workflow run $RUN_ID to complete..."
              gh run watch $RUN_ID --exit-status --interval 15
          fi 

      - name: Send notification to Slack
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "GitHub Action (BackEnd): ${{ vars.DOMAIN }} stopped! Status: ${{ job.status }}.\nEnvironment: ${{ env.ENVIRONMENT }}\nTriggered by: ${{ github.actor }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
