name: Terraform_deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy (prod, dev, dev_new)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - dev_new

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform deploy infrastructure
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      working-directory: terraform/infrastructure
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.working-directory }}

    steps:
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform apply
      run: terraform apply -auto-approve -input=false
